- name: vg_creation
  ansible.builtin.lvg: 
    pvs: /dev/sda3
    vg: "joe"
    pesize: 10M
    state: present

- name: lv_creation
  lvol: 
    vg: "joe"
    lv: "part1"
    size: "2G"
    resizefs: yes
    state: present
  tags:
    - part1
    - lv1

- name: lv2
  lvol:
    vg: "joe"
    lv: "part2"
    size: "2G"
    state: present
  tags:
    -lv2
    -part2

  
